defmodule Mook.Repo.Migrations.AddUserPubkeyAndDid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :hashed_password, :text, null: true
      modify :email, :citext, null: true
      add :public_key, :binary
      add :did, :text
      add :home_server, :text
      add :recovery_methods, :jsonb, null: false, default: fragment("'[]'::jsonb")
    end

    create unique_index(:users, [:did], name: "users_unique_did_index")

    create unique_index(:users, [:public_key], name: "users_unique_public_key_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:public_key], name: "users_unique_public_key_index")

    drop_if_exists unique_index(:users, [:did], name: "users_unique_did_index")

    alter table(:users) do
      remove :recovery_methods
      remove :home_server
      remove :did
      remove :public_key
      modify :email, :citext, null: false
      modify :hashed_password, :text, null: false
    end
  end
end
