export const tokens = {
  color: {
    "bg": "#202831",
    "bg2": "#1a2128",
    "surface": "#353E4B",
    "surface2": "#485363",
    "surface3": "#5a6776",
    "text": "#f0efea",
    "textSecondary": "#b5b9bf",
    "textTertiary": "#7a8290",
    "border": "#2a323d",
    "borderSoft": "#4a5464",
    "primary": "#d8ee4d",
    "primaryHover": "#c3d740",
    "primarySoft": "color-mix(in oklch, var(--color-primary) 22%, var(--color-surface))",
    "onPrimary": "#202831",
    "success": "#74cf86",
    "successSoft": "color-mix(in oklch, var(--color-success) 22%, var(--color-surface))",
    "warning": "#e8a06b",
    "warningSoft": "color-mix(in oklch, var(--color-warning) 22%, var(--color-surface))",
    "danger": "#e8615a",
    "dangerSoft": "color-mix(in oklch, var(--color-danger) 22%, var(--color-surface))",
  },
  space: {
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px",
    "2xl": "32px",
    "3xl": "48px",
  },
  radius: {
    "sm": "8px",
    "md": "12px",
    "lg": "18px",
    "xl": "22px",
    "pill": "999px",
  },
  font: {
    "family": "\"Geist\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", sans-serif",
    "mono": "\"Geist Mono\", ui-monospace, \"SF Mono\", Menlo, Consolas, monospace",
    "display": "\"Cal Sans\", \"Geist\", ui-sans-serif, system-ui, sans-serif",
    "xs": "0.75rem",
    "sm": "0.875rem",
    "base": "1rem",
    "lg": "1.25rem",
    "xl": "1.5rem",
    "2xl": "2rem",
    "3xl": "2.75rem",
  },
  shadow: {
    "tint": "8 12 18",
    "card": "0 1px 0 0 rgba(255,255,255,.02) inset, 0 6px 22px rgba(8,12,18,.28), 0 1px 2px rgba(8,12,18,.18)",
    "elev": "0 14px 40px rgba(8,12,18,.42), 0 4px 12px rgba(8,12,18,.22)",
  },
  ease: {
    "spring": "cubic-bezier(0.32, 0.72, 0, 1)",
    "outQuint": "cubic-bezier(0.22, 1, 0.36, 1)",
  },
  dur: {
    "fast": "180ms",
    "base": "280ms",
    "slow": "520ms",
  },
  glow: {
    "primarySm": "0 3px 10px color-mix(in oklch, var(--color-primary) 18%, transparent)",
    "primaryMd": "0 5px 16px color-mix(in oklch, var(--color-primary) 22%, transparent)",
    "primaryLg": "0 8px 22px color-mix(in oklch, var(--color-primary) 28%, transparent)",
    "successSm": "0 3px 10px color-mix(in oklch, var(--color-success) 20%, transparent)",
    "successMd": "0 5px 18px color-mix(in oklch, var(--color-success) 28%, transparent)",
    "successLg": "0 8px 24px color-mix(in oklch, var(--color-success) 34%, transparent)",
    "dangerSm": "0 3px 10px color-mix(in oklch, var(--color-danger) 20%, transparent)",
    "dangerMd": "0 5px 18px color-mix(in oklch, var(--color-danger) 28%, transparent)",
    "dangerLg": "0 8px 24px color-mix(in oklch, var(--color-danger) 34%, transparent)",
  },
  grad: {
    "surfaceWarm": "radial-gradient( ellipse at top, color-mix(in oklch, var(--color-primary) 8%, var(--color-surface)) 0%, var(--color-surface) 70% )",
    "surfaceCool": "radial-gradient( ellipse at top, color-mix(in oklch, var(--color-success) 8%, var(--color-surface)) 0%, var(--color-surface) 70% )",
    "surfaceSoft": "linear-gradient( 180deg, color-mix(in oklch, var(--color-text) 1.5%, var(--color-surface)) 0%, var(--color-surface) 60% )",
    "stageSuccess": "radial-gradient( ellipse at center 30%, color-mix(in oklch, var(--color-success) 8%, var(--color-surface)) 0%, var(--color-surface) 65% )",
    "stagePrimary": "radial-gradient( ellipse at top, color-mix(in oklch, var(--color-primary) 10%, var(--color-surface)) 0%, var(--color-surface) 60% )",
    "mobileWarm": "radial-gradient( ellipse at top, color-mix(in oklch, var(--color-primary) 8%, var(--color-bg)) 0%, var(--color-bg) 70% )",
    "mobileCool": "radial-gradient( ellipse at top, color-mix(in oklch, var(--color-success) 8%, var(--color-bg)) 0%, var(--color-bg) 70% )",
  },
  search: {
    "bg": "var(--color-bg)",
    "bgHover": "#1a2128",
    "borderFocus": "var(--color-primary)",
    "fg": "var(--color-text)",
    "fgPlaceholder": "var(--color-text-tertiary)",
    "icon": "var(--color-text-tertiary)",
    "height": "36px",
    "radius": "var(--radius-pill)",
    "paddingX": "14px",
    "gap": "10px",
    "font": "var(--font-sm)",
  },
  callCtrl: {
    "size": "56px",
    "bg": "var(--color-surface-2)",
    "fg": "var(--color-text)",
    "bgActive": "var(--color-primary)",
    "fgActive": "var(--color-on-primary)",
    "bgDanger": "var(--color-danger)",
    "fgDanger": "#fff",
    "bgAccept": "var(--color-success)",
  },
  misc: {
    "focusRing": "0 0 0 2px color-mix(in oklch, var(--color-primary) 70%, transparent)",
  },
} as const;

export type Tokens = typeof tokens;
