defmodule Yawp.Repo.Migrations.AddMessagesRoomFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "messages_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:messages, [:room_id])
  end

  def down do
    drop_if_exists index(:messages, [:room_id])

    drop constraint(:messages, "messages_room_id_fkey")

    alter table(:messages) do
      modify :room_id, :uuid
    end
  end
end
