defmodule Yawp.Repo.Migrations.AddRoomInviteResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:room_invites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :kind, :text, null: false, default: "single_use"
      add :uses_remaining, :bigint
      add :expires_at, :utc_datetime_usec, null: false
      add :consumed_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "room_invites_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :channel_id,
          references(:server_channels,
            column: :id,
            name: "room_invites_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :created_by_identity_id,
          references(:identities,
            column: :id,
            name: "room_invites_created_by_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:room_invites, [:token], name: "room_invites_unique_token_index")
  end

  def down do
    drop constraint(:room_invites, "room_invites_server_id_fkey")

    drop constraint(:room_invites, "room_invites_channel_id_fkey")

    drop constraint(:room_invites, "room_invites_created_by_identity_id_fkey")

    drop_if_exists unique_index(:room_invites, [:token], name: "room_invites_unique_token_index")

    drop table(:room_invites)
  end
end
