defmodule Yawp.Repo.Migrations.F725ChannelMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:channel_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :signature, :binary, null: false
      add :signed_by, :text, null: false
      add :server_inserted_at, :utc_datetime_usec, null: false

      add :channel_id,
          references(:server_channels,
            column: :id,
            name: "channel_messages_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :author_identity_id,
          references(:identities,
            column: :id,
            name: "channel_messages_author_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:channel_messages, "channel_messages_channel_id_fkey")

    drop constraint(:channel_messages, "channel_messages_author_identity_id_fkey")

    drop table(:channel_messages)
  end
end
