defmodule Yawp.Repo.Migrations.Attachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:server_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :upload_id, :text, null: false
      add :content_hash, :text, null: false
      add :mime, :text, null: false
      add :size_bytes, :bigint, null: false
      add :backend, :text, null: false
      add :backend_ref, :text, null: false
      add :uploaded_by_did, :text
      add :uploaded_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:server_attachments, [:upload_id],
             name: "server_attachments_unique_upload_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:server_attachments, [:upload_id],
                     name: "server_attachments_unique_upload_id_index"
                   )

    drop table(:server_attachments)
  end
end
