defmodule Yawp.Repo.Migrations.F715bMembershipAndIdentityActions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:server_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :identity_id,
          references(:identities,
            column: :id,
            name: "server_memberships_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :server_id,
          references(:servers,
            column: :id,
            name: "server_memberships_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :role_id,
          references(:server_roles,
            column: :id,
            name: "server_memberships_role_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:server_memberships, [:identity_id, :server_id],
             name: "server_memberships_unique_identity_server_index"
           )
  end

  def down do
    drop constraint(:server_memberships, "server_memberships_identity_id_fkey")

    drop constraint(:server_memberships, "server_memberships_server_id_fkey")

    drop constraint(:server_memberships, "server_memberships_role_id_fkey")

    drop_if_exists unique_index(:server_memberships, [:identity_id, :server_id],
                     name: "server_memberships_unique_identity_server_index"
                   )

    drop table(:server_memberships)
  end
end
