defmodule Yawp.Repo.Migrations.FullRbacSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:servers) do
      add :description, :text
      add :owner_did, :text
    end

    alter table(:server_roles) do
      remove :permissions
      add :permission_bits, :bigint, null: false, default: 0
      add :position, :bigint, null: false, default: 0
    end

    alter table(:server_memberships) do
      remove :role_id
      remove :inserted_at
      add :role_ids, {:array, :uuid}, null: false, default: []
      add :kind, :text, null: false, default: "anchored"
      add :banned, :boolean, null: false, default: false
      add :kicked, :boolean, null: false, default: false

      add :joined_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:server_channel_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :allow_bits, :bigint, null: false, default: 0
      add :deny_bits, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:server_channels,
            column: :id,
            name: "server_channel_overrides_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :role_id,
          references(:server_roles,
            column: :id,
            name: "server_channel_overrides_role_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :identity_id,
          references(:identities,
            column: :id,
            name: "server_channel_overrides_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:server_channel_overrides, "server_channel_overrides_channel_id_fkey")

    drop constraint(:server_channel_overrides, "server_channel_overrides_role_id_fkey")

    drop constraint(:server_channel_overrides, "server_channel_overrides_identity_id_fkey")

    drop table(:server_channel_overrides)

    alter table(:server_memberships) do
      remove :joined_at
      remove :kicked
      remove :banned
      remove :kind
      remove :role_ids

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role_id,
          references(:server_roles,
            column: :id,
            name: "server_memberships_role_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:server_roles) do
      remove :position
      remove :permission_bits
      add :permissions, :map, null: false, default: %{}
    end

    alter table(:servers) do
      remove :owner_did
      remove :description
    end
  end
end
