defmodule Yawp.Repo.Migrations.F716ServersRolesChannels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:servers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:server_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :system, :boolean, null: false, default: false
      add :permissions, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "server_roles_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:server_roles, [:server_id, :name],
             name: "server_roles_unique_server_id_name_index"
           )

    create table(:server_channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "server_channels_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:server_channels, [:server_id, :name],
             name: "server_channels_unique_server_id_name_index"
           )
  end

  def down do
    drop constraint(:server_channels, "server_channels_server_id_fkey")

    drop_if_exists unique_index(:server_channels, [:server_id, :name],
                     name: "server_channels_unique_server_id_name_index"
                   )

    drop table(:server_channels)

    drop constraint(:server_roles, "server_roles_server_id_fkey")

    drop_if_exists unique_index(:server_roles, [:server_id, :name],
                     name: "server_roles_unique_server_id_name_index"
                   )

    drop table(:server_roles)

    drop table(:servers)
  end
end
