defmodule Yawp.Repo.Migrations.AddFederationServerKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:federation_server_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key_id, :text, null: false
      add :public_key, :binary, null: false
      add :not_before, :utc_datetime_usec, null: false
      add :not_after, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_private_key, :binary, null: false
    end

    create unique_index(:federation_server_keys, [:key_id],
             name: "federation_server_keys_unique_key_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:federation_server_keys, [:key_id],
                     name: "federation_server_keys_unique_key_id_index"
                   )

    drop table(:federation_server_keys)
  end
end
