defmodule Yawp.Repo.Migrations.F722IdentityDeviceSubkeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identities) do
      add :device_subkeys, :map, null: false, default: fragment("'{\"subkeys\": []}'::jsonb")
      add :anchor_list, {:array, :text}, null: false, default: []
      add :profile_version, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:identities) do
      remove :profile_version
      remove :anchor_list
      remove :device_subkeys
    end
  end
end
