defmodule Yawp.Repo.Migrations.SignedServerReadMarkers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:server_read_markers) do
      add :signed_by, :text
      add :signature, :binary
    end

    execute "UPDATE server_read_markers SET signed_by = 'legacy', signature = decode(repeat('00', 64), 'hex') WHERE signed_by IS NULL OR signature IS NULL"

    alter table(:server_read_markers) do
      modify :signed_by, :text, null: false
      modify :signature, :binary, null: false
    end
  end

  def down do
    alter table(:server_read_markers) do
      remove :signature
      remove :signed_by
    end
  end
end
