defmodule Yawp.Repo.Migrations.FederationBlobSignatureColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identity_private_blobs) do
      add :public_key, :text
      add :signature, :text
    end
  end

  def down do
    alter table(:identity_private_blobs) do
      remove :signature
      remove :public_key
    end
  end
end
