defmodule Yawp.Repo.Migrations.DropLegacyChannelMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:channel_messages)
  end

  def down do
    # Rollback would require recreating the table manually
  end
end
