defmodule Yawp.Repo.Migrations.F715aFix2SingletonIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:admin_claim_tokens, [:id], name: "admin_claim_tokens_one_active_index")

    create index(:admin_claim_tokens, ["((1))"],
             name: "admin_claim_tokens_one_active_index",
             unique: true,
             using: "btree",
             where: "consumed_at IS NULL AND revoked_at IS NULL"
           )
  end

  def down do
    drop_if_exists index(:admin_claim_tokens, ["((1))"],
                     name: "admin_claim_tokens_one_active_index"
                   )

    create index(:admin_claim_tokens, [:id],
             name: "admin_claim_tokens_one_active_index",
             unique: true,
             using: "btree",
             where: "consumed_at IS NULL AND revoked_at IS NULL"
           )
  end
end
