defmodule Yawp.Repo.Migrations.F715aFixClaimTokenFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:admin_claim_tokens, [:id],
             name: "admin_claim_tokens_one_active_index",
             unique: true,
             using: "btree",
             where: "consumed_at IS NULL AND revoked_at IS NULL"
           )

    alter table(:admin_claim_tokens) do
      modify :created_by_account_id,
             references(:users,
               column: :id,
               name: "admin_claim_tokens_created_by_account_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:admin_claim_tokens, [:created_by_account_id])
  end

  def down do
    drop_if_exists index(:admin_claim_tokens, [:created_by_account_id])

    drop constraint(:admin_claim_tokens, "admin_claim_tokens_created_by_account_id_fkey")

    alter table(:admin_claim_tokens) do
      modify :created_by_account_id, :uuid
    end

    drop_if_exists index(:admin_claim_tokens, [:id], name: "admin_claim_tokens_one_active_index")
  end
end
