defmodule Yawp.Repo.Migrations.F715aAdminClaimToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:admin_claim_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :consumed_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec
      add :created_by_account_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:admin_claim_tokens, [:token],
             name: "admin_claim_tokens_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:admin_claim_tokens, [:token],
                     name: "admin_claim_tokens_unique_token_index"
                   )

    drop table(:admin_claim_tokens)
  end
end
