defmodule Yawp.Repo.Migrations.F723SessionAndRefreshTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_session_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false

      add :identity_id,
          references(:identities,
            column: :id,
            name: "identity_session_tokens_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id, :uuid, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:identity_session_tokens, [:token],
             name: "identity_session_tokens_unique_token_index"
           )

    create table(:identity_refresh_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false

      add :identity_id,
          references(:identities,
            column: :id,
            name: "identity_refresh_tokens_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id, :uuid, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :rotated_to,
          references(:identity_refresh_tokens,
            column: :id,
            name: "refresh_tokens_rotated_to_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:identity_refresh_tokens, [:token],
             name: "identity_refresh_tokens_unique_token_index"
           )
  end

  def down do
    drop constraint(:identity_refresh_tokens, "identity_refresh_tokens_identity_id_fkey")

    drop constraint(:identity_refresh_tokens, "refresh_tokens_rotated_to_fkey")

    drop_if_exists unique_index(:identity_refresh_tokens, [:token],
                     name: "identity_refresh_tokens_unique_token_index"
                   )

    drop table(:identity_refresh_tokens)

    drop constraint(:identity_session_tokens, "identity_session_tokens_identity_id_fkey")

    drop_if_exists unique_index(:identity_session_tokens, [:token],
                     name: "identity_session_tokens_unique_token_index"
                   )

    drop table(:identity_session_tokens)
  end
end
