defmodule Yawp.Repo.Migrations.ServerMessageStore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:servers) do
      add :body_archive_enabled, :boolean, null: false, default: false
    end

    create table(:server_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sender_did, :text, null: false
      add :body, :text
      add :mentions, {:array, :text}, null: false, default: []
      add :attachments, {:array, :map}, null: false, default: []
      add :sender_signature, :binary, null: false
      add :signed_by, :text, null: false
      add :server_serial, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_inserted_at, :utc_datetime_usec, null: false

      add :channel_id,
          references(:server_channels,
            column: :id,
            name: "server_messages_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :reply_to_message_id,
          references(:server_messages,
            column: :id,
            name: "server_messages_reply_to_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:server_messages, [:channel_id, :server_serial],
             name: "server_messages_unique_channel_serial_index"
           )

    create table(:server_message_tombstones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text, null: false
      add :actor_did, :text, null: false
      add :signature, :binary, null: false
      add :signed_by, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :message_id,
          references(:server_messages,
            column: :id,
            name: "server_message_tombstones_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:server_message_edits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :edit_serial, :bigint, null: false
      add :sender_signature, :binary, null: false
      add :signed_by, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :message_id,
          references(:server_messages,
            column: :id,
            name: "server_message_edits_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:server_message_edits, [:message_id, :edit_serial],
             name: "server_message_edits_unique_message_edit_serial_index"
           )

    create table(:server_archived_message_bodies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :message_id,
          references(:server_messages,
            column: :id,
            name: "server_archived_message_bodies_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(
           :server_archived_message_bodies,
           "server_archived_message_bodies_message_id_fkey"
         )

    drop table(:server_archived_message_bodies)

    drop constraint(:server_message_edits, "server_message_edits_message_id_fkey")

    drop_if_exists unique_index(:server_message_edits, [:message_id, :edit_serial],
                     name: "server_message_edits_unique_message_edit_serial_index"
                   )

    drop table(:server_message_edits)

    drop constraint(:server_message_tombstones, "server_message_tombstones_message_id_fkey")

    drop table(:server_message_tombstones)

    drop constraint(:server_messages, "server_messages_channel_id_fkey")

    drop constraint(:server_messages, "server_messages_reply_to_message_id_fkey")

    drop_if_exists unique_index(:server_messages, [:channel_id, :server_serial],
                     name: "server_messages_unique_channel_serial_index"
                   )

    drop table(:server_messages)

    alter table(:servers) do
      remove :body_archive_enabled
    end
  end
end
