defmodule Yawp.Repo.Migrations.ChannelsCategoriesStructure do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:server_channels) do
      add :position, :bigint, null: false, default: 0
      add :visibility, :text, null: false, default: "server_public"
      add :join_policy, :text, null: false, default: "invite_only"
      add :category_id, :uuid
    end

    create table(:server_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:server_channels) do
      modify :category_id,
             references(:server_categories,
               column: :id,
               name: "server_channels_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:server_categories) do
      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "server_categories_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :parent_id,
          references(:server_categories,
            column: :id,
            name: "server_categories_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:server_categories, [:server_id, :name],
             name: "server_categories_unique_server_id_name_index"
           )
  end

  def down do
    drop constraint(:server_categories, "server_categories_server_id_fkey")

    drop constraint(:server_categories, "server_categories_parent_id_fkey")

    drop_if_exists unique_index(:server_categories, [:server_id, :name],
                     name: "server_categories_unique_server_id_name_index"
                   )

    alter table(:server_categories) do
      remove :parent_id
      remove :server_id
      remove :inserted_at
      remove :position
      remove :name
    end

    drop constraint(:server_channels, "server_channels_category_id_fkey")

    alter table(:server_channels) do
      modify :category_id, :uuid
    end

    drop table(:server_categories)

    alter table(:server_channels) do
      remove :category_id
      remove :join_policy
      remove :visibility
      remove :position
    end
  end
end
