defmodule Yawp.Repo.Migrations.FederationInboxAndPpeBlobCache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_private_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :did, :text, null: false
      add :blob_version, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_ciphertext, :binary, null: false
    end

    create unique_index(:identity_private_blobs, [:did],
             name: "identity_private_blobs_unique_did_index"
           )

    create table(:identity_ppes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :did, :text, null: false
      add :display_name, :text
      add :avatar_ref, :text
      add :bio, :text
      add :profile_version, :bigint, null: false, default: 0
      add :envelope, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:identity_ppes, [:did], name: "identity_ppes_unique_did_index")

    create table(:federation_inbox_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recipient_did, :text, null: false
      add :envelope_id, :text, null: false
      add :conversation_id, :text
      add :kind, :text, null: false, default: "dm"
      add :envelope, :map, null: false
      add :inbox_serial, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:federation_inbox_entries, [:recipient_did, :envelope_id],
             name: "federation_inbox_entries_unique_envelope_index"
           )
  end

  def down do
    drop_if_exists unique_index(:federation_inbox_entries, [:recipient_did, :envelope_id],
                     name: "federation_inbox_entries_unique_envelope_index"
                   )

    drop table(:federation_inbox_entries)

    drop_if_exists unique_index(:identity_ppes, [:did], name: "identity_ppes_unique_did_index")

    drop table(:identity_ppes)

    drop_if_exists unique_index(:identity_private_blobs, [:did],
                     name: "identity_private_blobs_unique_did_index"
                   )

    drop table(:identity_private_blobs)
  end
end
