defmodule Yawp.Repo.Migrations.AddKickAndBanResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:server_kicks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "server_kicks_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :identity_id,
          references(:identities,
            column: :id,
            name: "server_kicks_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :kicked_by_identity_id,
          references(:identities,
            column: :id,
            name: "server_kicks_kicked_by_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:server_bans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "server_bans_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :identity_id,
          references(:identities,
            column: :id,
            name: "server_bans_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :banned_by_identity_id,
          references(:identities,
            column: :id,
            name: "server_bans_banned_by_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:server_bans, "server_bans_server_id_fkey")

    drop constraint(:server_bans, "server_bans_identity_id_fkey")

    drop constraint(:server_bans, "server_bans_banned_by_identity_id_fkey")

    drop table(:server_bans)

    drop constraint(:server_kicks, "server_kicks_server_id_fkey")

    drop constraint(:server_kicks, "server_kicks_identity_id_fkey")

    drop constraint(:server_kicks, "server_kicks_kicked_by_identity_id_fkey")

    drop table(:server_kicks)
  end
end
