defmodule Yawp.Repo.Migrations.F711AdminAccountArgon2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :confirmed_at
      modify :hashed_password, :text, null: false
      modify :email, :citext, null: false
      add :last_login_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:users) do
      remove :inserted_at
      remove :last_login_at
      modify :email, :citext, null: true
      modify :hashed_password, :text, null: true
      add :confirmed_at, :utc_datetime_usec
    end
  end
end
