defmodule Yawp.Repo.Migrations.DropPhase0ChatAndSplitUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists table(:messages)
    drop_if_exists table(:rooms)

    create table(:identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :did, :text, null: false
      add :master_public_key, :binary, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:identities, [:did], name: "identities_unique_did_index")

    create unique_index(:identities, [:master_public_key],
             name: "identities_unique_master_public_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:identities, [:master_public_key],
                     name: "identities_unique_master_public_key_index"
                   )

    drop_if_exists unique_index(:identities, [:did], name: "identities_unique_did_index")

    drop table(:identities)
  end
end
