defmodule Mook.Repo.Migrations.CreateMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :room_id, :uuid, null: false
      add :sender_did, :text, null: false
      add :content, :text, null: false
      add :ciphertext_envelope, :jsonb
      add :home_server, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:messages, [:room_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:messages, [:room_id, :inserted_at])

    drop table(:messages)
  end
end
