// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, IdentityResourceSchema, InferResult, RefreshTokenResourceSchema, RoomInviteResourceSchema, ServerBanResourceSchema, ServerCategoryFilterInput, ServerCategoryResourceSchema, ServerCategorySortField, ServerChannelFilterInput, ServerChannelResourceSchema, ServerChannelSortField, ServerKickResourceSchema, SortString, UUID, UnifiedFieldSelection, UtcDateTimeUsec, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type AcceptPeerRequestInput = {
  peerDid: string;
};

export type AcceptPeerRequestFields = UnifiedFieldSelection<IdentityResourceSchema>[];

export type InferAcceptPeerRequestResult<
  Fields extends AcceptPeerRequestFields | undefined,
> = InferResult<IdentityResourceSchema, Fields>;

export type AcceptPeerRequestResult<Fields extends AcceptPeerRequestFields | undefined = undefined> = | { success: true; data: InferAcceptPeerRequestResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Identity
 *
 * @ashActionType :update
 */
export async function acceptPeerRequest<Fields extends AcceptPeerRequestFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: { did: string };
  input: AcceptPeerRequestInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<AcceptPeerRequestResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "accept_peer_request",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<AcceptPeerRequestResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Identity
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateAcceptPeerRequest(
  config: {
  tenant?: string;
  identity: { did: string };
  input: AcceptPeerRequestInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "accept_peer_request",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type AddAnchorInput = {
  newAnchor: string;
  signedPpe?: Record<string, any> | null;
};

export type AddAnchorFields = UnifiedFieldSelection<IdentityResourceSchema>[];

export type InferAddAnchorResult<
  Fields extends AddAnchorFields | undefined,
> = InferResult<IdentityResourceSchema, Fields>;

export type AddAnchorResult<Fields extends AddAnchorFields | undefined = undefined> = | { success: true; data: InferAddAnchorResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Identity
 *
 * @ashActionType :update
 */
export async function addAnchor<Fields extends AddAnchorFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: { did: string };
  input: AddAnchorInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<AddAnchorResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "add_anchor",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<AddAnchorResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Identity
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateAddAnchor(
  config: {
  tenant?: string;
  identity: { did: string };
  input: AddAnchorInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "add_anchor",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type BindDeviceInput = {
  deviceId: UUID;
  devicePk: string;
  deviceSignature: string;
  senderSignature: string;
  deviceIssuedAt: string;
  requestIssuedAt: string;
};

export type BindDeviceFields = UnifiedFieldSelection<IdentityResourceSchema>[];

export type BindDeviceMetadata = {
  sessionToken?: string;
  refreshToken?: string;
  expiresAt?: UtcDateTimeUsec;
};

export type InferBindDeviceResult<
  Fields extends BindDeviceFields | undefined,
  MetadataFields extends ReadonlyArray<keyof BindDeviceMetadata> = []
> = InferResult<IdentityResourceSchema, Fields>;

export type BindDeviceResult<Fields extends BindDeviceFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof BindDeviceMetadata> = []> = | { success: true; data: InferBindDeviceResult<Fields>; metadata: Pick<BindDeviceMetadata, MetadataFields[number]>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Identity
 *
 * @ashActionType :update
 */
export async function bindDevice<Fields extends BindDeviceFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof BindDeviceMetadata> = []>(
  config: {
  tenant?: string;
  identity: { did: string };
  input: BindDeviceInput;
  fields?: Fields;
  metadataFields?: MetadataFields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<BindDeviceResult<Fields extends undefined ? [] : Fields, MetadataFields>> {
  const payload = {
    action: "bind_device",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields })
  };

  return executeActionRpcRequest<BindDeviceResult<Fields extends undefined ? [] : Fields, MetadataFields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Identity
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateBindDevice(
  config: {
  tenant?: string;
  identity: { did: string };
  input: BindDeviceInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "bind_device",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ClaimChatOwnerInput = {
  claimToken: string;
  did: string;
  pk: string;
  senderSignature: string;
};

export type ClaimChatOwnerFields = UnifiedFieldSelection<IdentityResourceSchema>[];

export type InferClaimChatOwnerResult<
  Fields extends ClaimChatOwnerFields | undefined,
> = InferResult<IdentityResourceSchema, Fields>;

export type ClaimChatOwnerResult<Fields extends ClaimChatOwnerFields | undefined = undefined> = | { success: true; data: InferClaimChatOwnerResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Identity
 *
 * @ashActionType :create
 */
export async function claimChatOwner<Fields extends ClaimChatOwnerFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: ClaimChatOwnerInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ClaimChatOwnerResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "claim_chat_owner",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ClaimChatOwnerResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Identity
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateClaimChatOwner(
  config: {
  tenant?: string;
  input: ClaimChatOwnerInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "claim_chat_owner",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RevokeDeviceSessionsInput = {
  deviceId: UUID;
};

export type RevokeDeviceSessionsFields = UnifiedFieldSelection<IdentityResourceSchema>[];

export type InferRevokeDeviceSessionsResult<
  Fields extends RevokeDeviceSessionsFields | undefined,
> = InferResult<IdentityResourceSchema, Fields>;

export type RevokeDeviceSessionsResult<Fields extends RevokeDeviceSessionsFields | undefined = undefined> = | { success: true; data: InferRevokeDeviceSessionsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Identity
 *
 * @ashActionType :update
 */
export async function revokeDeviceSessions<Fields extends RevokeDeviceSessionsFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: { did: string };
  input: RevokeDeviceSessionsInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RevokeDeviceSessionsResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "revoke_device_sessions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RevokeDeviceSessionsResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Identity
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRevokeDeviceSessions(
  config: {
  tenant?: string;
  identity: { did: string };
  input: RevokeDeviceSessionsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "revoke_device_sessions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SetReadReceiptsInput = {
  readReceiptsEnabled?: boolean;
};

export type SetReadReceiptsFields = UnifiedFieldSelection<IdentityResourceSchema>[];

export type InferSetReadReceiptsResult<
  Fields extends SetReadReceiptsFields | undefined,
> = InferResult<IdentityResourceSchema, Fields>;

export type SetReadReceiptsResult<Fields extends SetReadReceiptsFields | undefined = undefined> = | { success: true; data: InferSetReadReceiptsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Identity
 *
 * @ashActionType :update
 */
export async function setReadReceipts<Fields extends SetReadReceiptsFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: { did: string };
  input?: SetReadReceiptsInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetReadReceiptsResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_read_receipts",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetReadReceiptsResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Identity
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateSetReadReceipts(
  config: {
  tenant?: string;
  identity: { did: string };
  input?: SetReadReceiptsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_read_receipts",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RotateRefreshInput = {
  token: string;
};

export type RotateRefreshFields = UnifiedFieldSelection<RefreshTokenResourceSchema>[];

export type RotateRefreshMetadata = {
  sessionToken?: string;
  refreshToken?: string;
  expiresAt?: UtcDateTimeUsec;
};

export type InferRotateRefreshResult<
  Fields extends RotateRefreshFields | undefined,
  MetadataFields extends ReadonlyArray<keyof RotateRefreshMetadata> = []
> = InferResult<RefreshTokenResourceSchema, Fields>;

export type RotateRefreshResult<Fields extends RotateRefreshFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof RotateRefreshMetadata> = []> = | { success: true; data: InferRotateRefreshResult<Fields>; metadata: Pick<RotateRefreshMetadata, MetadataFields[number]>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new RefreshToken
 *
 * @ashActionType :create
 */
export async function rotateRefresh<Fields extends RotateRefreshFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof RotateRefreshMetadata> = []>(
  config: {
  tenant?: string;
  input: RotateRefreshInput;
  fields?: Fields;
  metadataFields?: MetadataFields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RotateRefreshResult<Fields extends undefined ? [] : Fields, MetadataFields>> {
  const payload = {
    action: "rotate_refresh",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields })
  };

  return executeActionRpcRequest<RotateRefreshResult<Fields extends undefined ? [] : Fields, MetadataFields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new RefreshToken
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateRotateRefresh(
  config: {
  tenant?: string;
  input: RotateRefreshInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "rotate_refresh",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type BanMemberInput = {
  reason?: string | null;
  serverId: UUID;
  identityId?: UUID | null;
  did?: string | null;
};

export type BanMemberFields = UnifiedFieldSelection<ServerBanResourceSchema>[];

export type InferBanMemberResult<
  Fields extends BanMemberFields | undefined,
> = InferResult<ServerBanResourceSchema, Fields>;

export type BanMemberResult<Fields extends BanMemberFields | undefined = undefined> = | { success: true; data: InferBanMemberResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Ban
 *
 * @ashActionType :create
 */
export async function banMember<Fields extends BanMemberFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: BanMemberInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<BanMemberResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "ban_member",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<BanMemberResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Ban
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateBanMember(
  config: {
  tenant?: string;
  input: BanMemberInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "ban_member",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateCategoryInput = {
  serverId: UUID;
  name: string;
  parentId?: UUID | null;
  position?: number;
};

export type CreateCategoryFields = UnifiedFieldSelection<ServerCategoryResourceSchema>[];

export type InferCreateCategoryResult<
  Fields extends CreateCategoryFields | undefined,
> = InferResult<ServerCategoryResourceSchema, Fields>;

export type CreateCategoryResult<Fields extends CreateCategoryFields | undefined = undefined> = | { success: true; data: InferCreateCategoryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Category
 *
 * @ashActionType :create
 */
export async function createCategory<Fields extends CreateCategoryFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateCategoryInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateCategoryResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_category",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateCategoryResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Category
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateCategory(
  config: {
  tenant?: string;
  input: CreateCategoryInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_category",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListCategoriesForServerInput = {
  serverId: UUID;
};

export type ListCategoriesForServerFields = UnifiedFieldSelection<ServerCategoryResourceSchema>[];
export type InferListCategoriesForServerResult<
  Fields extends ListCategoriesForServerFields,
> = Array<InferResult<ServerCategoryResourceSchema, Fields>>;

export type ListCategoriesForServerResult<Fields extends ListCategoriesForServerFields> = | { success: true; data: InferListCategoriesForServerResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Category records
 *
 * @ashActionType :read
 */
export async function listCategoriesForServer<Fields extends ListCategoriesForServerFields>(
  config: {
  tenant?: string;
  input: ListCategoriesForServerInput;
  fields: Fields;
  filter?: ServerCategoryFilterInput;
  sort?: SortString<ServerCategorySortField> | SortString<ServerCategorySortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListCategoriesForServerResult<Fields>> {
  const payload = {
    action: "list_categories_for_server",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListCategoriesForServerResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Category records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListCategoriesForServer(
  config: {
  tenant?: string;
  input: ListCategoriesForServerInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_categories_for_server",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ReorderCategoriesInput = {
  serverId: UUID;
  orderedIds: Array<UUID>;
};

export type InferReorderCategoriesResult = number;

export type ReorderCategoriesResult = | { success: true; data: InferReorderCategoriesResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Category
 *
 * @ashActionType :action
 */
export async function reorderCategories(
  config: {
  tenant?: string;
  input: ReorderCategoriesInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ReorderCategoriesResult> {
  const payload = {
    action: "reorder_categories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<ReorderCategoriesResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Category
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateReorderCategories(
  config: {
  tenant?: string;
  input: ReorderCategoriesInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "reorder_categories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateChannelInput = {
  serverId: UUID;
  categoryId?: UUID | null;
  name: string;
  type: "text" | "voice";
  position?: number;
  visibility?: "private" | "server_public";
  joinPolicy?: "invite_only" | "open";
};

export type CreateChannelFields = UnifiedFieldSelection<ServerChannelResourceSchema>[];

export type InferCreateChannelResult<
  Fields extends CreateChannelFields | undefined,
> = InferResult<ServerChannelResourceSchema, Fields>;

export type CreateChannelResult<Fields extends CreateChannelFields | undefined = undefined> = | { success: true; data: InferCreateChannelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Channel
 *
 * @ashActionType :create
 */
export async function createChannel<Fields extends CreateChannelFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateChannelInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateChannelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_channel",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateChannelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Channel
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateChannel(
  config: {
  tenant?: string;
  input: CreateChannelInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_channel",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DestroyChannelResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Channel
 *
 * @ashActionType :destroy
 */
export async function destroyChannel(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyChannelResult> {
  const payload = {
    action: "destroy_channel",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyChannelResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Channel
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyChannel(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_channel",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListTextChannelsFields = UnifiedFieldSelection<ServerChannelResourceSchema>[];
export type InferListTextChannelsResult<
  Fields extends ListTextChannelsFields,
> = Array<InferResult<ServerChannelResourceSchema, Fields>>;

export type ListTextChannelsResult<Fields extends ListTextChannelsFields> = | { success: true; data: InferListTextChannelsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Channel records
 *
 * @ashActionType :read
 */
export async function listTextChannels<Fields extends ListTextChannelsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ServerChannelFilterInput;
  sort?: SortString<ServerChannelSortField> | SortString<ServerChannelSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListTextChannelsResult<Fields>> {
  const payload = {
    action: "list_text_channels",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListTextChannelsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Channel records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListTextChannels(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_text_channels",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RecategorizeChannelInput = {
  categoryId?: UUID | null;
  position?: number;
};

export type RecategorizeChannelFields = UnifiedFieldSelection<ServerChannelResourceSchema>[];

export type InferRecategorizeChannelResult<
  Fields extends RecategorizeChannelFields | undefined,
> = InferResult<ServerChannelResourceSchema, Fields>;

export type RecategorizeChannelResult<Fields extends RecategorizeChannelFields | undefined = undefined> = | { success: true; data: InferRecategorizeChannelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Channel
 *
 * @ashActionType :update
 */
export async function recategorizeChannel<Fields extends RecategorizeChannelFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: RecategorizeChannelInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RecategorizeChannelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "recategorize_channel",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RecategorizeChannelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Channel
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRecategorizeChannel(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: RecategorizeChannelInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "recategorize_channel",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ReorderChannelsInput = {
  serverId: UUID;
  orderedIds: Array<UUID>;
};

export type InferReorderChannelsResult = number;

export type ReorderChannelsResult = | { success: true; data: InferReorderChannelsResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Channel
 *
 * @ashActionType :action
 */
export async function reorderChannels(
  config: {
  tenant?: string;
  input: ReorderChannelsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ReorderChannelsResult> {
  const payload = {
    action: "reorder_channels",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<ReorderChannelsResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Channel
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateReorderChannels(
  config: {
  tenant?: string;
  input: ReorderChannelsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "reorder_channels",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type KickMemberInput = {
  reason?: string | null;
  serverId: UUID;
  identityId?: UUID | null;
  did?: string | null;
};

export type KickMemberFields = UnifiedFieldSelection<ServerKickResourceSchema>[];

export type InferKickMemberResult<
  Fields extends KickMemberFields | undefined,
> = InferResult<ServerKickResourceSchema, Fields>;

export type KickMemberResult<Fields extends KickMemberFields | undefined = undefined> = | { success: true; data: InferKickMemberResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Kick
 *
 * @ashActionType :create
 */
export async function kickMember<Fields extends KickMemberFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: KickMemberInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<KickMemberResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "kick_member",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<KickMemberResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Kick
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateKickMember(
  config: {
  tenant?: string;
  input: KickMemberInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "kick_member",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateRoomInviteInput = {
  channelId: UUID;
  kind?: "multi_use" | "single_use" | null;
  ttlSeconds?: number | null;
  usesRemaining?: number | null;
};

export type CreateRoomInviteFields = UnifiedFieldSelection<RoomInviteResourceSchema>[];

export type InferCreateRoomInviteResult<
  Fields extends CreateRoomInviteFields | undefined,
> = InferResult<RoomInviteResourceSchema, Fields>;

export type CreateRoomInviteResult<Fields extends CreateRoomInviteFields | undefined = undefined> = | { success: true; data: InferCreateRoomInviteResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new RoomInvite
 *
 * @ashActionType :create
 */
export async function createRoomInvite<Fields extends CreateRoomInviteFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateRoomInviteInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateRoomInviteResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_room_invite",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateRoomInviteResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new RoomInvite
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateRoomInvite(
  config: {
  tenant?: string;
  input: CreateRoomInviteInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_room_invite",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RedeemRoomInviteInput = {
  token: string;
  did: string;
  pk: string;
  senderSignature: string;
};

export type RedeemRoomInviteFields = UnifiedFieldSelection<{serverId: UUID | null, channelId: UUID | null, kind: string | null, __type: "TypedMap", __primitiveFields: "serverId" | "channelId" | "kind"}>[];

export type InferRedeemRoomInviteResult<
  Fields extends RedeemRoomInviteFields | undefined,
> = InferResult<{serverId: UUID | null, channelId: UUID | null, kind: string | null, __type: "TypedMap", __primitiveFields: "serverId" | "channelId" | "kind"}, Fields>;

export type RedeemRoomInviteResult<Fields extends RedeemRoomInviteFields | undefined = undefined> = | { success: true; data: InferRedeemRoomInviteResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on RoomInvite
 *
 * @ashActionType :action
 */
export async function redeemRoomInvite<Fields extends RedeemRoomInviteFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RedeemRoomInviteInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RedeemRoomInviteResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "redeem_room_invite",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RedeemRoomInviteResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on RoomInvite
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRedeemRoomInvite(
  config: {
  tenant?: string;
  input: RedeemRoomInviteInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "redeem_room_invite",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RedeemServerInviteInput = {
  token: string;
  did: string;
  pk: string;
  senderSignature: string;
};

export type RedeemServerInviteFields = UnifiedFieldSelection<{serverId: UUID | null, role: string | null, __type: "TypedMap", __primitiveFields: "serverId" | "role"}>[];

export type InferRedeemServerInviteResult<
  Fields extends RedeemServerInviteFields | undefined,
> = InferResult<{serverId: UUID | null, role: string | null, __type: "TypedMap", __primitiveFields: "serverId" | "role"}, Fields>;

export type RedeemServerInviteResult<Fields extends RedeemServerInviteFields | undefined = undefined> = | { success: true; data: InferRedeemServerInviteResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on ServerInvite
 *
 * @ashActionType :action
 */
export async function redeemServerInvite<Fields extends RedeemServerInviteFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RedeemServerInviteInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RedeemServerInviteResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "redeem_server_invite",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RedeemServerInviteResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on ServerInvite
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRedeemServerInvite(
  config: {
  tenant?: string;
  input: RedeemServerInviteInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "redeem_server_invite",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

