// Generated by AshTypescript - Shared Types
// Do not edit this file manually



export type Binary = string;
export type UUID = string;
export type UtcDateTimeUsec = string;

// AdminAccount Schema
export type AdminAccountResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "lastLoginAt";
  id: UUID;
  email: string;
  lastLoginAt: UtcDateTimeUsec | null;
};



export type AdminAccountAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "lastLoginAt";
  id: UUID;
  email: string;
  lastLoginAt: UtcDateTimeUsec | null;
};


// DevicePushRegistry Schema
export type DevicePushRegistryResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "deviceSubkeyId" | "platform" | "token" | "updatedAt" | "identityId";
  id: UUID;
  deviceSubkeyId: UUID;
  platform: "apns" | "fcm";
  token: string;
  updatedAt: UtcDateTimeUsec;
  identityId: UUID;
  identity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
};



export type DevicePushRegistryAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "deviceSubkeyId" | "platform" | "token" | "updatedAt" | "identityId";
  id: UUID;
  deviceSubkeyId: UUID;
  platform: "apns" | "fcm";
  token: string;
  updatedAt: UtcDateTimeUsec;
  identityId: UUID;
};


// Identity Schema
export type IdentityResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "did" | "masterPublicKey" | "deviceSubkeys" | "anchorList" | "profileVersion" | "readReceiptsEnabled";
  id: UUID;
  did: string;
  masterPublicKey: Binary;
  deviceSubkeys: Record<string, any>;
  anchorList: Array<string>;
  profileVersion: number;
  readReceiptsEnabled: boolean;
};



export type IdentityAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "did" | "masterPublicKey" | "deviceSubkeys" | "anchorList" | "profileVersion" | "readReceiptsEnabled";
  id: UUID;
  did: string;
  masterPublicKey: Binary;
  deviceSubkeys: Record<string, any>;
  anchorList: Array<string>;
  profileVersion: number;
  readReceiptsEnabled: boolean;
};


// NotificationPreference Schema
export type NotificationPreferenceResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "serverId" | "channelId" | "conversationId" | "level" | "identityId";
  id: UUID;
  serverId: UUID | null;
  channelId: UUID | null;
  conversationId: string | null;
  level: "all" | "mentions_only" | "muted";
  identityId: UUID;
  identity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
};



export type NotificationPreferenceAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "serverId" | "channelId" | "conversationId" | "level" | "identityId";
  id: UUID;
  serverId: UUID | null;
  channelId: UUID | null;
  conversationId: string | null;
  level: "all" | "mentions_only" | "muted";
  identityId: UUID;
};


// RefreshToken Schema
export type RefreshTokenResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "token" | "identityId" | "deviceId" | "expiresAt" | "revokedAt" | "rotatedTo";
  id: UUID;
  token: string;
  identityId: UUID;
  deviceId: UUID;
  expiresAt: UtcDateTimeUsec;
  revokedAt: UtcDateTimeUsec | null;
  rotatedTo: UUID | null;
  identity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
  rotatedToRefresh: { __type: "Relationship"; __resource: RefreshTokenResourceSchema | null; };
};



export type RefreshTokenAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "token" | "identityId" | "deviceId" | "expiresAt" | "revokedAt" | "rotatedTo";
  id: UUID;
  token: string;
  identityId: UUID;
  deviceId: UUID;
  expiresAt: UtcDateTimeUsec;
  revokedAt: UtcDateTimeUsec | null;
  rotatedTo: UUID | null;
};


// ServerBan Schema
export type ServerBanResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "serverId" | "identityId" | "bannedByIdentityId";
  id: UUID;
  reason: string | null;
  serverId: UUID;
  identityId: UUID;
  bannedByIdentityId: UUID | null;
  identity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
  bannedByIdentity: { __type: "Relationship"; __resource: IdentityResourceSchema | null; };
};



export type ServerBanAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "serverId" | "identityId" | "bannedByIdentityId";
  id: UUID;
  reason: string | null;
  serverId: UUID;
  identityId: UUID;
  bannedByIdentityId: UUID | null;
};


// ServerCategory Schema
export type ServerCategoryResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "position" | "serverId" | "parentId";
  id: UUID;
  name: string;
  position: number;
  serverId: UUID;
  parentId: UUID | null;
  parent: { __type: "Relationship"; __resource: ServerCategoryResourceSchema | null; };
};



export type ServerCategoryAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "position" | "serverId" | "parentId";
  id: UUID;
  name: string;
  position: number;
  serverId: UUID;
  parentId: UUID | null;
};


// ServerChannel Schema
export type ServerChannelResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "type" | "position" | "visibility" | "joinPolicy" | "retention" | "retentionDurationMs" | "serverId" | "categoryId";
  id: UUID;
  name: string;
  type: "text" | "voice";
  position: number;
  visibility: "private" | "server_public";
  joinPolicy: "invite_only" | "open";
  retention: "duration_ms" | "forever" | null;
  retentionDurationMs: number | null;
  serverId: UUID;
  categoryId: UUID | null;
  category: { __type: "Relationship"; __resource: ServerCategoryResourceSchema | null; };
};



export type ServerChannelAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "type" | "position" | "visibility" | "joinPolicy" | "retention" | "retentionDurationMs" | "serverId" | "categoryId";
  id: UUID;
  name: string;
  type: "text" | "voice";
  position: number;
  visibility: "private" | "server_public";
  joinPolicy: "invite_only" | "open";
  retention: "duration_ms" | "forever" | null;
  retentionDurationMs: number | null;
  serverId: UUID;
  categoryId: UUID | null;
};


// ServerKick Schema
export type ServerKickResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "serverId" | "identityId" | "kickedByIdentityId";
  id: UUID;
  reason: string | null;
  serverId: UUID;
  identityId: UUID;
  kickedByIdentityId: UUID | null;
  identity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
  kickedByIdentity: { __type: "Relationship"; __resource: IdentityResourceSchema | null; };
};



export type ServerKickAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "serverId" | "identityId" | "kickedByIdentityId";
  id: UUID;
  reason: string | null;
  serverId: UUID;
  identityId: UUID;
  kickedByIdentityId: UUID | null;
};


// ServerMessage Schema
export type ServerMessageResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "senderDid" | "body" | "mentions" | "attachments" | "senderSignature" | "signedBy" | "serverSerial" | "serverInsertedAt" | "channelId" | "replyToMessageId";
  id: UUID;
  senderDid: string;
  body: string | null;
  mentions: Array<string>;
  attachments: Array<Record<string, any>>;
  senderSignature: Binary;
  signedBy: string;
  serverSerial: number;
  serverInsertedAt: UtcDateTimeUsec;
  channelId: UUID;
  replyToMessageId: UUID | null;
  channel: { __type: "Relationship"; __resource: ServerChannelResourceSchema; };
  replyToMessage: { __type: "Relationship"; __resource: ServerMessageResourceSchema | null; };
};



export type ServerMessageAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "senderDid" | "body" | "mentions" | "attachments" | "senderSignature" | "signedBy" | "serverSerial" | "serverInsertedAt" | "channelId" | "replyToMessageId";
  id: UUID;
  senderDid: string;
  body: string | null;
  mentions: Array<string>;
  attachments: Array<Record<string, any>>;
  senderSignature: Binary;
  signedBy: string;
  serverSerial: number;
  serverInsertedAt: UtcDateTimeUsec;
  channelId: UUID;
  replyToMessageId: UUID | null;
};


// RoomInvite Schema
export type RoomInviteResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "token" | "kind" | "usesRemaining" | "expiresAt" | "consumedAt" | "revokedAt" | "serverId" | "channelId" | "createdByIdentityId";
  id: UUID;
  token: string;
  kind: "multi_use" | "single_use";
  usesRemaining: number | null;
  expiresAt: UtcDateTimeUsec;
  consumedAt: UtcDateTimeUsec | null;
  revokedAt: UtcDateTimeUsec | null;
  serverId: UUID;
  channelId: UUID;
  createdByIdentityId: UUID;
  channel: { __type: "Relationship"; __resource: ServerChannelResourceSchema; };
  createdByIdentity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
};



export type RoomInviteAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "token" | "kind" | "usesRemaining" | "expiresAt" | "consumedAt" | "revokedAt" | "serverId" | "channelId" | "createdByIdentityId";
  id: UUID;
  token: string;
  kind: "multi_use" | "single_use";
  usesRemaining: number | null;
  expiresAt: UtcDateTimeUsec;
  consumedAt: UtcDateTimeUsec | null;
  revokedAt: UtcDateTimeUsec | null;
  serverId: UUID;
  channelId: UUID;
  createdByIdentityId: UUID;
};


// ServerInvite Schema
export type ServerInviteResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "token" | "kind" | "usesRemaining" | "expiresAt" | "consumedAt" | "revokedAt" | "serverId" | "createdByIdentityId";
  id: UUID;
  token: string;
  kind: "multi_use" | "single_use";
  usesRemaining: number | null;
  expiresAt: UtcDateTimeUsec;
  consumedAt: UtcDateTimeUsec | null;
  revokedAt: UtcDateTimeUsec | null;
  serverId: UUID;
  createdByIdentityId: UUID;
  createdByIdentity: { __type: "Relationship"; __resource: IdentityResourceSchema; };
};



export type ServerInviteAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "token" | "kind" | "usesRemaining" | "expiresAt" | "consumedAt" | "revokedAt" | "serverId" | "createdByIdentityId";
  id: UUID;
  token: string;
  kind: "multi_use" | "single_use";
  usesRemaining: number | null;
  expiresAt: UtcDateTimeUsec;
  consumedAt: UtcDateTimeUsec | null;
  revokedAt: UtcDateTimeUsec | null;
  serverId: UUID;
  createdByIdentityId: UUID;
};


export type AdminAccountFilterInput = {
  and?: Array<AdminAccountFilterInput>;
  or?: Array<AdminAccountFilterInput>;
  not?: Array<AdminAccountFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  lastLoginAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };



};
export type DevicePushRegistryFilterInput = {
  and?: Array<DevicePushRegistryFilterInput>;
  or?: Array<DevicePushRegistryFilterInput>;
  not?: Array<DevicePushRegistryFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  deviceSubkeyId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  platform?: {
    eq?: "apns" | "fcm";
    notEq?: "apns" | "fcm";
    in?: Array<"apns" | "fcm">;
  };

  token?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  identityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  identity?: IdentityFilterInput;

};
export type IdentityFilterInput = {
  and?: Array<IdentityFilterInput>;
  or?: Array<IdentityFilterInput>;
  not?: Array<IdentityFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  did?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  masterPublicKey?: {
    eq?: Binary;
    notEq?: Binary;
    in?: Array<Binary>;
  };

  deviceSubkeys?: {
    eq?: Record<string, any>;
    notEq?: Record<string, any>;
    in?: Array<Record<string, any>>;
  };

  anchorList?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
  };

  profileVersion?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  readReceiptsEnabled?: {
    eq?: boolean;
    notEq?: boolean;
  };



};
export type NotificationPreferenceFilterInput = {
  and?: Array<NotificationPreferenceFilterInput>;
  or?: Array<NotificationPreferenceFilterInput>;
  not?: Array<NotificationPreferenceFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  channelId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  conversationId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  level?: {
    eq?: "all" | "mentions_only" | "muted";
    notEq?: "all" | "mentions_only" | "muted";
    in?: Array<"all" | "mentions_only" | "muted">;
  };

  identityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  identity?: IdentityFilterInput;

};
export type RefreshTokenFilterInput = {
  and?: Array<RefreshTokenFilterInput>;
  or?: Array<RefreshTokenFilterInput>;
  not?: Array<RefreshTokenFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  token?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  identityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  deviceId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  expiresAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  revokedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  rotatedTo?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  identity?: IdentityFilterInput;

  rotatedToRefresh?: RefreshTokenFilterInput;

};
export type ServerBanFilterInput = {
  and?: Array<ServerBanFilterInput>;
  or?: Array<ServerBanFilterInput>;
  not?: Array<ServerBanFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  reason?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  identityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  bannedByIdentityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  identity?: IdentityFilterInput;

  bannedByIdentity?: IdentityFilterInput;

};
export type ServerCategoryFilterInput = {
  and?: Array<ServerCategoryFilterInput>;
  or?: Array<ServerCategoryFilterInput>;
  not?: Array<ServerCategoryFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  position?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  parentId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  parent?: ServerCategoryFilterInput;

};
export type ServerChannelFilterInput = {
  and?: Array<ServerChannelFilterInput>;
  or?: Array<ServerChannelFilterInput>;
  not?: Array<ServerChannelFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  type?: {
    eq?: "text" | "voice";
    notEq?: "text" | "voice";
    in?: Array<"text" | "voice">;
  };

  position?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  visibility?: {
    eq?: "private" | "server_public";
    notEq?: "private" | "server_public";
    in?: Array<"private" | "server_public">;
  };

  joinPolicy?: {
    eq?: "invite_only" | "open";
    notEq?: "invite_only" | "open";
    in?: Array<"invite_only" | "open">;
  };

  retention?: {
    eq?: "duration_ms" | "forever";
    notEq?: "duration_ms" | "forever";
    in?: Array<"duration_ms" | "forever">;
    isNil?: boolean;
  };

  retentionDurationMs?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  categoryId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  category?: ServerCategoryFilterInput;

};
export type ServerKickFilterInput = {
  and?: Array<ServerKickFilterInput>;
  or?: Array<ServerKickFilterInput>;
  not?: Array<ServerKickFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  reason?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  identityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  kickedByIdentityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  identity?: IdentityFilterInput;

  kickedByIdentity?: IdentityFilterInput;

};
export type ServerMessageFilterInput = {
  and?: Array<ServerMessageFilterInput>;
  or?: Array<ServerMessageFilterInput>;
  not?: Array<ServerMessageFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  senderDid?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  mentions?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
  };

  attachments?: {
    eq?: Array<Record<string, any>>;
    notEq?: Array<Record<string, any>>;
    in?: Array<Array<Record<string, any>>>;
  };

  senderSignature?: {
    eq?: Binary;
    notEq?: Binary;
    in?: Array<Binary>;
  };

  signedBy?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  serverSerial?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  serverInsertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  channelId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  replyToMessageId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  channel?: ServerChannelFilterInput;

  replyToMessage?: ServerMessageFilterInput;

};
export type RoomInviteFilterInput = {
  and?: Array<RoomInviteFilterInput>;
  or?: Array<RoomInviteFilterInput>;
  not?: Array<RoomInviteFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  token?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  kind?: {
    eq?: "multi_use" | "single_use";
    notEq?: "multi_use" | "single_use";
    in?: Array<"multi_use" | "single_use">;
  };

  usesRemaining?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  expiresAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  consumedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  revokedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  channelId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  createdByIdentityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  channel?: ServerChannelFilterInput;

  createdByIdentity?: IdentityFilterInput;

};
export type ServerInviteFilterInput = {
  and?: Array<ServerInviteFilterInput>;
  or?: Array<ServerInviteFilterInput>;
  not?: Array<ServerInviteFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  token?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  kind?: {
    eq?: "multi_use" | "single_use";
    notEq?: "multi_use" | "single_use";
    in?: Array<"multi_use" | "single_use">;
  };

  usesRemaining?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  expiresAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  consumedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  revokedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  serverId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  createdByIdentityId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  createdByIdentity?: IdentityFilterInput;

};


export const adminAccountFilterFields = ["id", "email", "lastLoginAt"] as const;
export type AdminAccountFilterField = (typeof adminAccountFilterFields)[number];

export const devicePushRegistryFilterFields = ["id", "deviceSubkeyId", "platform", "token", "updatedAt", "identityId", "identity"] as const;
export type DevicePushRegistryFilterField = (typeof devicePushRegistryFilterFields)[number];

export const identityFilterFields = ["id", "did", "masterPublicKey", "deviceSubkeys", "anchorList", "profileVersion", "readReceiptsEnabled"] as const;
export type IdentityFilterField = (typeof identityFilterFields)[number];

export const notificationPreferenceFilterFields = ["id", "serverId", "channelId", "conversationId", "level", "identityId", "identity"] as const;
export type NotificationPreferenceFilterField = (typeof notificationPreferenceFilterFields)[number];

export const refreshTokenFilterFields = ["id", "token", "identityId", "deviceId", "expiresAt", "revokedAt", "rotatedTo", "identity", "rotatedToRefresh"] as const;
export type RefreshTokenFilterField = (typeof refreshTokenFilterFields)[number];

export const serverBanFilterFields = ["id", "reason", "serverId", "identityId", "bannedByIdentityId", "server", "identity", "bannedByIdentity"] as const;
export type ServerBanFilterField = (typeof serverBanFilterFields)[number];

export const serverCategoryFilterFields = ["id", "name", "position", "serverId", "parentId", "server", "parent"] as const;
export type ServerCategoryFilterField = (typeof serverCategoryFilterFields)[number];

export const serverChannelFilterFields = ["id", "name", "type", "position", "visibility", "joinPolicy", "retention", "retentionDurationMs", "serverId", "categoryId", "server", "category"] as const;
export type ServerChannelFilterField = (typeof serverChannelFilterFields)[number];

export const serverKickFilterFields = ["id", "reason", "serverId", "identityId", "kickedByIdentityId", "server", "identity", "kickedByIdentity"] as const;
export type ServerKickFilterField = (typeof serverKickFilterFields)[number];

export const serverMessageFilterFields = ["id", "senderDid", "body", "mentions", "attachments", "senderSignature", "signedBy", "serverSerial", "serverInsertedAt", "channelId", "replyToMessageId", "channel", "replyToMessage"] as const;
export type ServerMessageFilterField = (typeof serverMessageFilterFields)[number];

export const roomInviteFilterFields = ["id", "token", "kind", "usesRemaining", "expiresAt", "consumedAt", "revokedAt", "serverId", "channelId", "createdByIdentityId", "server", "channel", "createdByIdentity"] as const;
export type RoomInviteFilterField = (typeof roomInviteFilterFields)[number];

export const serverInviteFilterFields = ["id", "token", "kind", "usesRemaining", "expiresAt", "consumedAt", "revokedAt", "serverId", "createdByIdentityId", "server", "createdByIdentity"] as const;
export type ServerInviteFilterField = (typeof serverInviteFilterFields)[number];


export const adminAccountSortFields = ["id", "email", "lastLoginAt"] as const;
export type AdminAccountSortField = (typeof adminAccountSortFields)[number];

export const devicePushRegistrySortFields = ["id", "deviceSubkeyId", "platform", "token", "updatedAt", "identityId"] as const;
export type DevicePushRegistrySortField = (typeof devicePushRegistrySortFields)[number];

export const identitySortFields = ["id", "did", "masterPublicKey", "deviceSubkeys", "anchorList", "profileVersion", "readReceiptsEnabled"] as const;
export type IdentitySortField = (typeof identitySortFields)[number];

export const notificationPreferenceSortFields = ["id", "serverId", "channelId", "conversationId", "level", "identityId"] as const;
export type NotificationPreferenceSortField = (typeof notificationPreferenceSortFields)[number];

export const refreshTokenSortFields = ["id", "token", "identityId", "deviceId", "expiresAt", "revokedAt", "rotatedTo"] as const;
export type RefreshTokenSortField = (typeof refreshTokenSortFields)[number];

export const serverBanSortFields = ["id", "reason", "serverId", "identityId", "bannedByIdentityId"] as const;
export type ServerBanSortField = (typeof serverBanSortFields)[number];

export const serverCategorySortFields = ["id", "name", "position", "serverId", "parentId"] as const;
export type ServerCategorySortField = (typeof serverCategorySortFields)[number];

export const serverChannelSortFields = ["id", "name", "type", "position", "visibility", "joinPolicy", "retention", "retentionDurationMs", "serverId", "categoryId"] as const;
export type ServerChannelSortField = (typeof serverChannelSortFields)[number];

export const serverKickSortFields = ["id", "reason", "serverId", "identityId", "kickedByIdentityId"] as const;
export type ServerKickSortField = (typeof serverKickSortFields)[number];

export const serverMessageSortFields = ["id", "senderDid", "body", "mentions", "attachments", "senderSignature", "signedBy", "serverSerial", "serverInsertedAt", "channelId", "replyToMessageId"] as const;
export type ServerMessageSortField = (typeof serverMessageSortFields)[number];

export const roomInviteSortFields = ["id", "token", "kind", "usesRemaining", "expiresAt", "consumedAt", "revokedAt", "serverId", "channelId", "createdByIdentityId"] as const;
export type RoomInviteSortField = (typeof roomInviteSortFields)[number];

export const serverInviteSortFields = ["id", "token", "kind", "usesRemaining", "expiresAt", "consumedAt", "revokedAt", "serverId", "createdByIdentityId"] as const;
export type ServerInviteSortField = (typeof serverInviteSortFields)[number];


// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };




